# --- grammar_resources.py ---

# ==============================================================================
# == Part 1: (Tagalog Sentence Patterns) ==
# ==============================================================================
# THIS IS THE RESOURCE WHICH IS NEEDED FOR THE SCRIPT
# KINDA IS LIKE  A MODEL FOR THE CFG OF THE CODE'
# THIS NEEDS TO BE UPDATED FOR IT TO BE TRANSLATING
# SENTENCES MORE PROPERLY

structural_rules = [
    # Core Structures
    ("S", ["NP", "AY", "VP"]),       ("S", ["NP", "VP"]),
    ("S", ["VP", "NP"]),           ("S", ["VP"]),
    ("S", ["Adj", "NP"]),          
    ("S", ["Adv", "S"]),           
    ("S", ["Interjection", "S"]),  
    ("S", ["CONJ", "S"]),          
    ("S", ["NP", "Adv"]),          

    # Question Structures
    ("S", ["VP", "NP_BA"]),      ("S", ["NP", "VP_BA"]),
    ("VP_NP_BA", ["VP", "NP_BA"]), ("NP_BA", ["NP", "BA"]),
    ("S", ["Interrogative", "NP"]), ("S", ["Interrogative", "NP_BA"]),
    ("S", ["Interrogative", "VP"]),
    ("S", ["V", "NP", "Adv", "BA"]),
    ("S", ["Kailan", "BA", "VP"]),
    ("S", ["Interrogative", "DET", "N"]),  
    ("S", ["Interrogative", "N"]), 
    ("S", ["Adj", "NP_BA"]), 
    ("S", ["Interrogative", "NP", "Adv"]), 
    ("S", ["Interrogative", "Adv", "NP"]), 

    # Other Sentence Types
    ("S", ["Interjection", "NP", "Adv"]), ("S", ["V", "NP", "Adv"]),
    ("S", ["Interjection", "Adv", "Adv"]),
    ("S", ["Adv", "VP"]),
    ("S", ["Particle", "VP"]), ("S", ["VP", "Particle"]),
    ("S", ["VP", "Adv"]),
    ("S", ["Existential", "NP"]),
    ("S", ["P", "N", "VP"]),
    ("S", ["VP", "CONJ", "Adj", "NP"]),
    ("S", ["NP", "AY", "Adj"]),  
    ("S", ["V", "NP", "PP"]), 
    ("S", ["V", "NP", "Adv"]), 
    ("S", ["V", "PP", "Adv"]), 
    ("S", ["V", "NP", "PP", "Adv"]), 
    ("S", ["V", "Particle"]), 
    ("S", ["V", "NP", "Particle"]), 
    ("S", ["NP", "V", "NP"]), 
    ("S", ["NP", "V", "NP", "PP"]), 
    ("S", ["V", "V"]), 
    ("S", ["V", "NP", "V"]), 
    ("S", ["NP", "V", "Adv"]), 
    ("S", ["NP", "Adv", "NP"]), 
    ("S", ["V", "NP", "PP"]), 
    ("S", ["NP", "V"]), 
    ("S", ["Adj", "Adv"]), 
    ("S", ["NP", "Adv", "Adj"]), 
    ("S", ["NP", "Adv", "V"]), 
    ("S", ["V", "NP", "Adv", "PP"]), 
    ("S", ["NP", "NP"]), 
    ("S", ["NP", "V", "NP", "PP"]), 
    ("S", ["Existential", "NP", "Adv", "V", "PP"]), 
    ("S", ["Interrogative", "V"]), 

    # Phrase Structures
    ("VP", ["V"]), ("VP", ["V", "NP"]), ("VP", ["V", "PP"]), ("VP", ["V", "Adv"]),
    ("VP", ["V", "Adj"]), ("VP", ["V", "Particle"]), ("VP", ["VP", "Adv"]),
    ("VP", ["VP", "PP"]), ("VP", ["VP", "CONJ", "VP"]), ("VP", ["V", "NP", "PP"]),
    ("VP", ["V", "PP", "PP"]), ("VP", ["V", "V"]),
    ("VP", ["V", "DET", "N"]),  
    ("VP", ["V", "NP", "Adv"]), 
    ("VP", ["V", "NP", "Particle"]), 
    ("VP", ["V", "PP"]), 
    ("VP", ["V", "NP", "V"]), 
    ("VP", ["V", "Adv"]), 
    ("VP", ["V", "NP", "Adv"]), 
    ("VP", ["V", "NP", "PP"]), 
    ("VP", ["V", "NP", "Adv", "PP"]), 
    ("VP", ["V", "Particle"]), 
    ("VP", ["V", "NP", "Particle"]), 
    ("VP", ["V", "NP", "PP", "Adv"]), 
    ("VP", ["V", "NP", "Adv", "V"]), 
    ("VP", ["V", "Adv", "PP"]), 


    ("NP", ["Pronoun"]), ("NP", ["ProperName"]), ("NP", ["DET", "N"]),
    ("NP", ["N"]), ("NP", ["DT_NG", "N"]), ("NP", ["NP", "PP"]),
    ("NP", ["Adj", "N"]), ("NP", ["DET", "Adj", "N"]), ("NP", ["NP", "CONJ", "NP"]),
    ("NP", ["DET", "PluralN"]), ("NP", ["MGA", "N"]), ("NP", ["NP", "Particle"]),
    ("NP", ["Number", "N"]), ("NP", ["Number", "Adj", "N"]), ("NP", ["NP", "N"]),
    ("NP", ["Existential", "N"]),
    ("NP", ["N", "PP"]),
    ("NP", ["Adv", "NP"]), 
    ("NP", ["DET", "N", "PP"]),
    ("NP", ["N", "N"]), 
    ("NP", ["DET", "Adj"]), 
    ("NP", ["Adj", "NP"]), 
    ("NP", ["Number", "Adj", "N"]), 
    ("NP", ["DET", "N", "Adj"]), 
    ("NP", ["NP", "Adv"]), 
    ("NP", ["NP", "PP"]), 
    ("NP", ["NP", "V"]), 
    ("NP", ["NP", "CONJ", "NP"]), 
    ("NP", ["DET", "N", "Particle", "NP"]), 
    ("NP", ["Adj", "N", "NP"]), 


    ("PP", ["P", "NP"]), ("PP", ["P", "N"]), ("PP", ["P", "ProperName"]),
    ("PP", ["P", "Phrase"]),
    ("PP", ["P", "NP", "PP"]), 
    ("PP", ["P", "Adv"]), 
    ("PP", ["P", "V"]), 


    ("Adj", ["Adj"]),
    ("Adj", ["Adv", "Adj"]),       
    ("Adj", ["Adj", "CONJ", "Adj"]),
    ("Adj", ["Adj", "Particle"]),   
    ("Adj", ["V", "Adj"]), 
    ("Adj", ["Adj", "NP"]), 
    ("Adj", ["Adj", "CONJ", "Adj"]), 

    # Plural Noun structure (kept for clarity, though NP rule added)
    ("PluralN", ["MGA", "N"]),

    
    ("S", ["NP", "V", "NP"]), 
    ("S", ["V", "NP", "Adv", "PP"]), 
    ("S", ["NP", "AY", "V", "NP"]), 
    ("S", ["NP", "AY", "V", "NP", "PP"]), 
    ("S", ["Adv", "NP", "V"]), 
    ("S", ["Adv", "NP", "V", "Adv"]), 
    ("S", ["V", "NP", "PP", "NP"]), 
    ("S", ["V", "Particle"]), 
    ("S", ["V", "NP", "Particle"]), 
    ("S", ["V", "NP", "PP"]), 
    ("S", ["NP", "V"]), 
    ("S", ["Adj", "Adv"]), 
    ("S", ["NP", "Adj", "NP"]), 
    ("S", ["NP", "Adv", "V", "NP"]), 
    ("S", ["V", "NP", "Adv", "PP", "NP"]), 
    ("S", ["Existential", "NP", "Adv", "V", "PP"]), 
    ("S", ["Interrogative", "V"]), 
    ("S", ["NP", "Adj"]), 
    ("S", ["V", "NP", "PP", "NP", "PP"]), 
    ("S", ["Existential", "NP", "Adv", "V", "PP"]), 
    ("S", ["V", "NP", "CONJ", "V", "NP"]), 
    ("S", ["NP", "V", "NP", "Adv"]), 
    ("S", ["V", "NP", "Adv"]), 
    ("S", ["V", "NP"]), 
    ("S", ["NP", "NP", "Adv"]), 
    ("S", ["NP", "NP"]), 
    ("S", ["V", "NP", "PP"]), 
    ("S", ["NP", "V", "PP", "Adv"]), 
    ("S", ["Adv", "NP", "Adv"]), 
    ("S", ["V", "NP", "NP"]), 
    ("S", ["NP", "V", "PP"]), 
    ("S", ["NP", "NP", "PP"]), 
    ("S", ["NP", "NP"]), 
    ("S", ["NP", "Adj", "NP", "PP"]), 
    ("S", ["V", "NP", "Adv", "NP"]), 
    ("S", ["Existential", "NP", "PP"]), 
    ("S", ["V", "NP"]), 
    ("S", ["NP", "V", "PP"]), 
    ("S", ["V", "NP"]), 
    ("S", ["Adv", "NP", "V", "NP", "PP"]), 
    ("S", ["NP", "NP", "Adv"]), 
    ("S", ["V", "NP"]), 
    ("S", ["Adj", "NP", "Adv", "NP"]), 
    ("S", ["V", "Adv", "NP"]), 
    ("S", ["Adj", "NP", "PP"]), 
    ("S", ["V", "NP"]), 
    ("S", ["V", "NP", "PP"]), 
    ("S", ["V", "NP", "Adv", "V"]), 
    ("S", ["Adv", "NP", "V", "PP", "NP"]), 
    ("S", ["Adv", "NP", "V", "PP"]), 
    ("S", ["V", "NP", "CONJ", "V", "PP"]), 
    ("S", ["V", "NP", "V", "PP"]), 
    ("S", ["Existential", "NP", "Adv", "V", "PP"]), 
    ("S", ["Interrogative", "V"]), 
    ("S", ["Adj", "NP"]), 
    ("S", ["Adv", "NP", "V"]), 
    ("S", ["V", "NP", "Adv", "PP", "NP"]), 


]

# ==============================================================================
# == Part 2: (Tagalog Word List with Part-of-Speech Tags) ==
# ==============================================================================
# --- Added latest batch of frequent/needed words with *best-guess* POS tags ---
# --- !!! PLEASE REVIEW AND VERIFY THESE TAGS !!! ---
# --- Includes words and some inflected forms found in the TSV ---
lexicon_definitions = [
    # Determiners (Markers)
    ("DET", "ang"), ("DET", "si"), ("DET", "sina"),
    ("DT_NG", "ng"), ("DT_NG", "ni"), ("DT_NG", "nina"),
    ("MGA", "mga"), ("DET", "yung"), ("DET", "yong"), 
    ("DET", "ito'y"), # ito + ay

    # Particles / Special Markers
    ("BA", "ba"), ("AY", "ay"), ("Particle", "po"),
    ("Particle", "lang"), ("Particle", "pa"), ("Particle", "raw"), ("Particle", "eh"),
    ("Particle", "bang"),
    ("Particle", "pang"),
    ("Particle", "sana"),
    ("Particle", "yan"),
    ("Particle", "na"),
    ("Particle", "din"),
    ("Particle", "rin"),
    ("Particle", "pala"),
    ("Particle", "lang"), 
    ("Particle", "naman"), 

    # Pronouns (Including common combinations with linkers - simplified)
    ("Pronoun", "ako"), ("Pronoun", "ikaw"), ("Pronoun", "siya"), ("Pronoun", "ko"),
    ("Pronoun", "mo"), ("Pronoun", "niya"), ("Pronoun", "tayo"), ("Pronoun", "kami"),
    ("Pronoun", "kayo"), ("Pronoun", "sila"), ("Pronoun", "ka"), ("Pronoun", "kita"),
    ("Pronoun", "kang"), ("Pronoun", "ito"),
    ("Pronoun", "siyang"), ("Pronoun", "kong"), ("Pronoun", "akong"), ("Pronoun", "kanya"),
    ("Pronoun", "akin"), ("Pronoun", "natin"), ("Pronoun", "niyang"), ("Pronoun", "itong"),
    ("Pronoun", "isa"), ("Pronoun", "niyo"), ("Pronoun", "kanyang"),
    ("Pronoun", "atin-atin"), ("Pronoun", "iyon"),
    ("Pronoun", "walang"),
    ("Pronoun", "silang"),
    ("Pronoun", "namin"),
    ("Pronoun", "niya"),
    ("Pronoun", "ko'y"),
    ("Pronoun", "niyang"), 
    ("Pronoun", "kanyang"), 
    ("Pronoun", "ka'y"), 

    # Proper Names
    ("ProperName", "maria"), ("ProperName", "pedro"), ("ProperName", "juan"), ("ProperName", "pilipinas"),
    ("ProperName", "america"),("ProperName", "nancy"), ("ProperName", "ingles"),
    ("ProperName", "pasko"), ("ProperName", "tokyo"), ("ProperName", "ginoong"),
    ("ProperName", "norton"),("ProperName", "mayuko"),("ProperName", "betty"),
    ("ProperName", "tsina"), ("ProperName", "diyos"),
    ("ProperName", "mary"),
    ("ProperName", "judy"),
    ("ProperName", "ken"),
    ("ProperName", "japan"),
    ("ProperName", "aleman"),
    ("ProperName", "australia"),
    ("ProperName", "hapon"), 

    # Verbs (Includes some common inflected forms from the TSV)
    ("V", "kumain"), ("V", "nagluto"), ("V", "tumakbo"), ("V", "uminom"), ("V", "naglakad"),
    ("V", "kumusta"), ("V", "kamusta"), ("V", "pupunta"), ("V", "umuulan"), ("V", "pakiabot"),
    ("V", "huwag"), ("V", "magalala"),("V", "mabuhay"), ("V", "tulungan"), ("V", "tama"),
    ("V", "marunong"), ("V", "gusto"), ("V", "nakatira"), ("V", "nagaaral"),
    ("V", "may"), ("V", "wala"), ("V", "sabihin"), ("V", "dumating"), ("V", "pumunta"),
    ("V", "nakita"), ("V", "magtrabaho"),("V", "dapat"), ("V", "magdadala"),
    ("V", "isinilang"), ("V", "pinagkalooban"), ("V", "magpalagayan"), ("V", "intindihin"),
    ("V", "natutulog"), ("V", "magalit"), ("V", "nagbebenta"), ("V", "nais"), ("V", "maging"),
    ("V", "nagsasaulo"), ("V", "magpakasaya"), ("V", "gumaling"), ("V", "binili"),
    ("V", "papasukan"), ("V", "nakalipas"), ("V", "makatrabaho"), ("V", "nagtagumpay"),
    ("V", "sumunod"), ("V", "kailangang"), ("V", "kakalakad"), ("V", "ihinahain"),
    ("V", "magreretiro"), ("V", "iniisip"), ("V", "ayaw"), ("V", "nag-uusap"), ("V", "sinasabi"),
    ("V", "ibig"), ("V", "nakarating"), ("V", "masasabi"), ("V", "makikiraan"), ("V", "nagkasakit"),
    ("V", "kumuha"), ("V", "nananatili"), ("V", "bumalik"), ("V", "nakalalamang"),
    ("V", "tinanggihan"),("V", "iwasan"), ("V", "nabigyan"), ("V", "kailangan"),
    ("V", "nahuli"), ("V", "maimbento"), ("V", "mayroon"), ("V", "magsulat"), ("V", "umalis"),
    ("V", "iniwasan"), ("V", "nagtatrabaho"), ("V", "bumili"), ("V", "nawala"),
    ("V", "magsisimula"), ("V", "kalimutang"), ("V", "magdala"), ("V", "papunta"),
    ("V", "alam"),
    ("V", "maglakad"),
    ("V", "makakaasa"),
    ("V", "pumasok"),
    ("V", "darating"),
    ("V", "pumili"),
    ("V", "ginawa"),
    ("V", "makakapunta"),
    ("V", "lumikha"),
    ("V", "basahin"),
    ("V", "magsasalita"),
    ("V", "magpapalaki"),
    ("V", "nakuha"),
    ("V", "nabigo"),
    ("V", "talunin"),
    ("V", "humihiram"),
    ("V", "mahilig"),
    ("V", "magbasa"),
    ("V", "mahiyain"),
    ("V", "magsisimula"),
    ("V", "mahina"),
    ("V", "lalabas"),
    ("V", "maglalayag"),
    ("V", "sinunog"),
    ("V", "galing"),
    ("V", "sinuwerte"),
    ("V", "dumamba"),
    ("V", "magaling"),
    ("V", "dumalo"),
    ("V", "maabutan"),
    ("V", "natapos"),
    ("V", "magandang"),
    ("V", "makukuha"),
    ("V", "masasabing"),
    ("V", "makikiraan"), 
    ("V", "nagkasakit"), 
    ("V", "nananatili"), 
    ("V", "nakalalamang"), 
    ("V", "tinanggihan"), 
    ("V", "nabigyan"), 
    ("V", "nahuli"), 
    ("V", "maimbento"), 
    ("V", "nagtatrabaho"), 
    ("V", "nawala"), 
    ("V", "kalimutang"), 
    ("V", "sinasabi"), 
    ("V", "nakarating"), 
    ("V", "masasabi"), 
    ("V", "kumuha"), 
    ("V", "bumalik"), 
    ("V", "iwasan"), 
    ("V", "pumunta"), 
    ("V", "dumating"), 
    ("V", "isinilang"), 
    ("V", "pinagkalooban"), 
    ("V", "magpalagayan"), 
    ("V", "intindihin"), 
    ("V", "natutulog"), 
    ("V", "nagbebenta"), 
    ("V", "nagsasaulo"), 
    ("V", "magpakasaya"), 
    ("V", "gumaling"), 
    ("V", "binili"), 
    ("V", "papasukan"), 
    ("V", "nagtagumpay"), 
    ("V", "sumunod"), 
    ("V", "kakalakad"), 
    ("V", "ihinahain"), 
    ("V", "magreretiro"), 
    ("V", "iniisip"), 
    ("V", "nag-uusap"), 
    ("V", "humihiram"), 
    ("V", "maglalayag"), 
    ("V", "sinuwerte"), 
    ("V", "dumalo"), 
    ("V", "maabutan"), 
    ("V", "makatrabaho"), 
    ("V", "magsisimula"), 
    ("V", "magdala"), 
    ("V", "basahin"), 
    ("V", "magsasalita"), 
    ("V", "magpapalaki"), 
    ("V", "sinunog"), 
    ("V", "dumamba"), 
    ("V", "magbasa"), 
    ("V", "mamatay"), 
    ("V", "hanap"), 
    ("V", "hinahanap"), 
    ("V", "makakaasa"), 
    ("V", "pumasok"), 
    ("V", "makukuha"), 


    # Prepositions
    ("P", "sa"), ("P", "nasa"), ("P", "para"), ("P", "tungkol"), ("P", "harap"), ("P", "bago"),
    ("P", "hanggang"),
    ("P", "mula"),
    ("P", "kay"),
    ("P", "ng"), 
    # Adverbs (Includes some common inflected forms from the TSV)
    ("Adv", "mabilis"), ("Adv", "kahapon"), ("Adv", "na"), ("Adv", "agad"),
    ("Adv", "ngayon"), ("Adv", "diyan"), ("Adv", "hindi"), ("Adv", "palagi"),
    ("Adv", "doon"), ("Adv", "nang"), ("Adv", "kaya"), ("Adv", "kahit"), ("Adv", "paano"),
    ("Adv", "ngayong"), ("Adv", "noong"),
    ("Adv", "kada"), ("Adv", "araw-araw"),
    ("Adv", "arawaraw"),
    ("Adv", "madalas"), ("Adv", "harap-harapan"), ("Adv", "kadalasang"), ("Adv", "gaano"),
    ("Adv", "katagal"), ("Adv", "muna"), ("Adv", "dati"), ("Adv", "maagang"), ("Adv", "totoo"),
    ("Adv", "mas"),
    ("Adv", "halos"),
    ("Adv", "lang"),
    ("Adv", "pa"),
    ("Adv", "raw"),
    ("Adv", "din"),
    ("Adv", "rin"),
    ("Adv", "mukhang"),
    ("Adv", "ganito"),
    ("Adv", "noon"),
    ("Adv", "biglang"),
    ("Adv", "pala"),
    ("Adv", "lamang"),
    ("Adv", "lubos"),
    ("Adv", "bigla"),
    ("Adv", "naman"),
    ("Adv", "talaga"),
    ("Adv", "minsan"),
    ("Adv", "doon"), 
    ("Adv", "ngayon"), 
    ("Adv", "bukas"), 
    ("Adv", "rito"), 
    ("Adv", "dito"), 
    ("Adv", "saan"), 
    ("Adv", "nasaan"), 

    # Nouns (Includes some common inflected forms from the TSV)
    ("N", "bata"), ("N", "aso"), ("N", "pusa"), ("N", "bahay"), ("N", "pagkain"),
    ("N", "asin"), ("N", "panahon"), ("N", "guro"), ("N", "pangalan"), ("N", "banyo"),
    ("N", "araw"), ("N", "oras"), ("N", "gabi"), ("N", "sinigang"), ("N", "libro"), ("N", "tubig"),
    ("N", "kaligayahan"), ("N", "lahat"), ("N", "pamamagitan"), ("N", "eroplano"),
    ("N", "susi"), ("N", "kotse"), ("N", "salamin"), ("N", "bag"), ("N", "payong"),
    ("N", "taon"), ("N", "trabaho"), ("N", "silid"), ("N", "anak"), ("N", "lalaki"),
    ("N", "gulang"), ("N", "taong"),
    ("N", "opisina"), ("N", "mundo"), ("N", "tao"), ("N", "karangalan"), ("N", "karapatan"),
    ("N", "katwiran"), ("N", "budhi"), ("N", "diwa"), ("N", "pagkakapatiran"), ("N", "pakiusap"),
    ("N", "ideya"), ("N", "kulay"), ("N", "gamot"), ("N", "botika"), ("N", "kaibigan"),
    ("N", "salita"), ("N", "sipnayan"), ("N", "parke"), ("N", "pasko"), ("N", "klase"),
    ("N", "mestiza"), ("N", "pagsusubok"), ("N", "paaralan"), ("N", "museo"), ("N", "karne"),
    ("N", "tingin"), ("N", "party"), ("N", "telepono"), ("N", "meeting"), ("N", "paliparan"),
    ("N", "paglipad"), ("N", "balita"), ("N", "estudyante"), ("N", "club"), ("N", "activities"),
    ("N", "pangkat"), ("N", "tsismis"), ("N", "boss"), ("N", "beach"),
    ("N", "pag-asa"), ("N", "pintura"), ("N", "pagnanakaw"), ("N", "computer"),
    ("N", "kasangkapan"), ("N", "sanaysay"), ("N", "pagkakaibigan"), ("N", "barko"),
    ("N", "web"), ("N", "page"), ("N", "yugto"), ("N", "bagyo"),
    ("N", "pakiramdam"), ("N", "problema"), ("N", "kapakanan"),
    ("N", "taong-bayan"),("N", "camera"), ("N", "kapatid"),
    ("N", "asong"), ("N", "tiwala"), ("N", "linggo"), ("N", "kaalamalam"),
    ("N", "pagsnow"),
    ("N", "babae"),
    ("N", "pera"),
    ("N", "lolo"),
    ("N", "hapon"), # Can be ProperName (Japanese) or Noun (afternoon)
    ("N", "istasyon"),
    ("N", "uri"),
    ("N", "kape"),
    ("N", "puno"),
    ("N", "tren"),
    ("N", "umaga"),
    ("N", "gusali"),
    ("N", "makina"),
    ("N", "ale"),
    ("N", "mund"),
    ("N", "dyaryo"),
    ("N", "pagsasalita"),
    ("N", "hayop"),
    ("N", "binhi"),
    ("N", "mansanas"),
    ("N", "atleta"),
    ("N", "tauhan"),
    ("N", "digmaan"),
    ("N", "katotohanan"),
    ("N", "lottery"),
    ("N", "ginhawa"),
    ("N", "kalsada"),
    ("N", "anak"), 
    ("N", "lalaki"), 
    ("N", "gulang"), 
    ("N", "taong"), 
    ("N", "opisina"), 
    ("N", "mundo"), 
    ("N", "tao"), 
    ("N", "karangalan"), 
    ("N", "karapatan"), 
    ("N", "katwiran"), 
    ("N", "budhi"), 
    ("N", "diwa"), 
    ("N", "pagkakapatiran"), 
    ("N", "pakiusap"), 
    ("N", "ideya"), 
    ("N", "kulay"), 
    ("N", "gamot"), 
    ("N", "botika"), 
    ("N", "kaibigan"), 
    ("N", "salita"), 
    ("N", "sipnayan"), 
    ("N", "paaralan"), 
    ("N", "museo"), 
    ("N", "karne"), 
    ("N", "tingin"), 
    ("N", "party"), 
    ("N", "telepono"), 
    ("N", "meeting"), 
    ("N", "paliparan"), 
    ("N", "paglipad"), 
    ("N", "balita"), 
    ("N", "estudyante"), 
    ("N", "club"), 
    ("N", "activities"), 
    ("N", "pangkat"), 
    ("N", "tsismis"), 
    ("N", "boss"), 
    ("N", "beach"), 
    ("N", "pintura"), 
    ("N", "computer"), 
    ("N", "kasangkapan"), 
    ("N", "sanaysay"), 
    ("N", "barko"), 
    ("N", "bagyo"), 
    ("N", "pakiramdam"), 
    ("N", "problema"), 
    ("N", "kapakanan"), 
    ("N", "camera"), 
    ("N", "kapatid"), 
    ("N", "tiwala"), 
    ("N", "linggo"), 
    ("N", "kaalamalam"), 
    ("N", "pagsnow"), 
    ("N", "pagnanakaw"), 
    ("N", "pagkakaibigan"), 
    ("N", "web"), 
    ("N", "page"), 
    ("N", "yugto"), 
    ("N", "taong-bayan"), 
    ("N", "asong"), 
    ("N", "dyaryo"), 
    ("N", "atleta"), 
    ("N", "tauhan"), 
    ("N", "binhi"), 
    ("N", "mansanas"), 
    ("N", "digmaan"), 
    ("N", "ginhawa"), 
    ("N", "kalsada"), 
    ("N", "lotto"), 
    ("N", "high"), 
    ("N", "school"), 
    ("N", "station"), 
    ("N", "bus"), 
    ("N", "party"), 
    ("N", "party?"), 
    ("N", "party."), 
    ("N", "party,"), 
    ("N", "computer,"), 
    ("N", "computer."), 
    ("N", "party"), 
    ("N", "computer"), 
    ("N", "club"), 
    ("N", "activities"), 


    # Adjectives (Includes some common inflected forms from the TSV)
    ("Adj", "maganda"), ("Adj", "isang"), ("Adj", "mahal"), ("Adj", "mabuti"),
    ("Adj", "maraming"),("Adj", "mukhang"), ("Adj", "tama"), ("Adj", "wala"),
    ("Adj", "bagong"), ("Adj", "malaya"), ("Adj", "pantay-pantay"), ("Adj", "berde"),
    ("Adj", "ingles"), ("Adj", "masarap"), ("Adj", "kainit"), ("Adj", "pagod"),
    ("Adj", "sigurado"), ("Adj", "magkaiba"), ("Adj", "tatlong"), ("Adj", "ika-10"),
    ("Adj", "konti"), ("Adj", "mala-calculator"), ("Adj", "pinakamalalang"),
    ("Adj", "pinakamahalagang"), ("Adj", "totoo"), ("Adj", "susunod"), ("Adj", "malakas"),
    ("Adj", "mahirap"),
    ("Adj", "unang"),
    ("Adj", "malapit"),
    ("Adj", "masamang"),
    ("Adj", "putla"),
    ("Adj", "mainit-init"),
    ("Adj", "kaakit-akit"),
    ("Adj", "mahina"),
    ("Adj", "buong"),
    ("Adj", "naputla"),
    ("Adj", "payapa"),
    ("Adj", "berde"), 
    ("Adj", "ingles"), 
    ("Adj", "pagod"), 
    ("Adj", "sigurado"), 
    ("Adj", "magkaiba"), 
    ("Adj", "tatlong"), 
    ("Adj", "ika-10"), 
    ("Adj", "konti"), 
    ("Adj", "mala-calculator"), 
    ("Adj", "pinakamalalang"), 
    ("Adj", "pinakamahalagang"), 
    ("Adj", "totoo"), 
    ("Adj", "susunod"), 
    ("Adj", "malakas"), 
    ("Adj", "mahirap"), 
    ("Adj", "unang"), 
    ("Adj", "malapit"), 
    ("Adj", "masamang"), 
    ("Adj", "putla"), 
    ("Adj", "mainit-init"), 
    ("Adj", "kaakit-akit"), 
    ("Adj", "mahina"), 
    ("Adj", "buong"), 
    ("Adj", "naputla"), 
    ("Adj", "buong"), 
    ("Adj", "badtrip"), 


    # Interjections
    ("Interjection", "oo"), ("Interjection", "salamat"), ("Interjection", "pasensya"),
    ("Interjection", "tara"), ("Interjection", "kumusta"), ("Interjection", "kamusta"),
    ("Interjection", "hoy"),
    ("Interjection", "nakuha"),

    # Interrogatives (Question Words)
    ("Interrogative", "ano"), ("Interrogative", "anong"), ("Interrogative", "saan"),
    ("Interrogative", "nasaan"), ("Interrogative", "paano"), ("Interrogative", "gaano"),
    ("Interrogative", "aling"), ("Interrogative", "kailan"),
    ("Interrogative", "sino"),
    ("Interrogative", "sino'ng"),
    ("Interrogative", "paano"), 
    ("Interrogative", "gaano"), 
    ("Interrogative", "aling"), 
    ("Interrogative", "kailan"), 


    # Conjunctions
    ("CONJ", "at"), ("CONJ", "nang"), ("CONJ", "kaya"), ("CONJ", "dahil"), ("CONJ", "kahit"),
    ("CONJ", "kung"), ("CONJ", "bago"), ("CONJ", "tapos"), ("CONJ", "pero"),
    ("CONJ", "kapag"),
    ("CONJ", "mula"),
    ("CONJ", "nang"), 
    ("CONJ", "pero"), 


    # Numbers
    ("Number", "sampung"), ("Number", "19"), ("Number", "30"),
    ("Number", "tatlong"),
    ("Number", "ika-5"),
    ("Number", "ika-10"),

    # Other - need to verify POS
    ("Particle", "ba"), 
    ("Punctuation", "?"), 
    ("Punctuation", "."), 
    ("Punctuation", ","), 
    ("Punctuation", "!"), 
    ("Punctuation", "\""), 
    ("Punctuation", "-"), 
]


# ==============================================================================
# == Part 3: Bilingual Dictionary (Tagalog -> English Word Map) ==
# ==============================================================================
# --- Added translations for newly added lexicon words ---
translation_dictionary = {
    # Pronouns
    "ako": "i", "ikaw": "you", "siya": "he/she", "niya": "his/her", "kanya": "his/her",
    "ka": "you", "mo": "you/your", "tayo": "we (incl.)", "kami": "we (excl.)",
    "kayo": "you (pl.)", "sila": "they", "kita": "i->you", "kang": "you", "ito": "this",
    "siyang": "he/she", "kong": "my", "akong": "i", "natin": "our (incl.)", "akin": "my/mine",
    "niyang": "his/her", "itong": "this", "isa": "one", "niyo":"you(pl)/your(pl)", "kanyang": "his/her",
    "atin-atin": "among ourselves", "iyon": "that", "silang":"they", "namin":"our (excl.)",
    "niya": "his/her",
    "ko'y": "i am",
    "ito'y": "this is",
    "ka'y": "you are", 

    # Proper Names
    "maria": "maria", "pedro": "pedro", "juan": "juan", "pilipinas": "philippines",
    "america": "america", "nancy": "nancy", "ingles": "english", "pasko": "christmas",
    "tokyo": "tokyo", "ginoong": "mr", "norton": "norton", "mayuko": "mayuko", "betty": "betty",
    "tsina": "china", "diyos": "god", "mary": "mary",
    "judy": "judy",
    "ken": "ken",
    "japan": "japan",
    "aleman": "german",
    "australia": "australia",
    "hapon": "japanese", 

    # Verbs (Includes translations for some common inflected forms)
    "kumain": "ate/eaten", "nagluto": "cooked", "tumakbo": "ran", "uminom": "drank",
    "naglakad": "walked", "kumusta": "how is/are", "kamusta": "how is/are",
    "pupunta": "will go", "umuulan": "raining", "pakiabot": "please pass", "huwag": "don't",
    "magalala": "worry", "mabuhay": "live/long live", "tulungan": "help", "tama": "is correct/correct",
    "marunong": "know how", "gusto": "like/want", "nakatira": "live at", "nagaaral": "studying",
    "may": "have/has/there is", "wala": "none/don't have/lacking", "sabihin": "say", "dumating": "arrived",
    "pumunta": "went", "nakita": "saw", "magtrabaho": "to work", "dapat": "should/must",
    "magdadala": "will bring", "isinilang": "was born", "pinagkalooban": "endowed",
    "magpalagayan": "act towards", "intindihin": "understand/mind", "natutulog": "sleeping",
    "magalit": "get angry", "nagbebenta": "selling", "nais": "want/wish", "maging": "to be/become",
    "nagsasaulo": "memorizing", "magpakasaya": "be happy", "gumaling": "improved/got well",
    "binili": "bought", "papasukan": "will enter/apply for", "nakalipas": "passed",
    "makatrabaho": "work with", "nagtagumpay": "succeeded", "sumunod": "followed",
    "kailangang": "need to", "kakalakad": "walking (repetitive)", "ihinahain": "serving",
    "magreretiro": "will retire", "iniisip": "thinking", "ayaw": "don't want",
    "nag-uusap": "talking", "sinasabi": "saying", "ibig": "want/mean", "nakarating": "arrived",
    "masasabi": "can say", "makikiraan": "will pass by", "nagkasakit": "got sick",
    "kumuha": "to get/take", "nananatili": "staying", "bumalik": "return",
    "nakalalamang": "winning/prevailing", "tinanggihan": "denied", "iwasan": "avoid",
    "nabigyan": "was given", "kailangan": "need", "nahuli": "was caught/late",
    "maimbento": "be invented", "mayroon": "have/there is", "magsulat": "to write",
    "umalis": "left", "iniwasan": "avoided", "nagtatrabaho": "working", "bumili": "bought",
    "nawala": "lost/disappeared", "magsisimula": "will start", "kalimutang": "forget",
    "magdala": "to bring",
    "papunta": "going to",
    "alam": "know",
    "maglakad": "to walk",
    "makakaasa": "can expect/rely",
    "pumasok": "entered/went",
    "darating": "will arrive",
    "pumili": "choose",
    "ginawa": "did/made",
    "makakapunta": "can go",
    "lumikha": "created",
    "basahin": "read",
    "magsasalita": "will talk",
    "magpapalaki": "will grow",
    "nakuha": "got",
    "nabigo": "failed/disappointed",
    "talunin": "defeat/beat",
    "humihiram": "borrowing",
    "mahilig": "fond of",
    "magbasa": "reading",
    "mahiyain": "shy",
    "magsisimula": "will start",
    "mahina": "weak",
    "lalabas": "will come out",
    "maglalayag": "will sail/take off",
    "sinunog": "burned",
    "galing": "from",
    "sinuwerte": "got lucky",
    "dumamba": "jumped",
    "magaling": "good/skillful",
    "dumalo": "attended",
    "maabutan": "catch up",
    "natapos": "finished",
    "magandang": "is good",
    "makukuha": "can get/obtain",
    "masasabing": "can be said",
    "mamatay": "die", 
    "hanap": "search/look for", 
    "hinahanap": "looking for", 


    # Prepositions
    "sa": "to/at/in", "nasa": "is at/in", "para": "for", "tungkol": "about", "harap": "front", "bago": "before",
    "hanggang": "until/up to",
    "mula": "from",
    "kay": "to/from (person)",
    "ng": "of", 


    # Adverbs (Includes translations for some common inflected forms)
    "mabilis": "quickly", "kahapon": "yesterday", "na": "now/already", "agad": "immediately",
    "ngayon": "today/now", "diyan": "there", "hindi": "not", "palagi": "always",
    "doon": "there (far)", "nang": "when/of/so that", "kaya": "so/maybe/can", "kahit": "even if/although", "paano": "how",
    "ngayong": "this", "noong": "then (past)",
    "kada": "each/per",
    "araw-araw": "every day", "arawaraw": "every day",
    "madalas": "often", "harap-harapan": "face-to-face",
    "kadalasang": "often", "gaano": "how much/many", "katagal": "how long", "muna": "first/for now",
    "dati": "before/formerly", "raw": "(reportedly)", "eh": "(informal particle)",
    "bago": "before/new", "tapos": "finished/then", "mas":"more", "hanggang":"until/up to",
    "sana":"hopefully", "yan":"that (informal)", "halos":"almost",
    "lang": "only/just",
    "pa": "yet/still",
    "raw": "(reportedly)",
    "din": "also",
    "rin": "also",
    "mukhang": "looks/seems",
    "ganito": "this way/like this",
    "noon": "then/before",
    "biglang": "suddenly",
    "pala": "(particle indicating realization)",
    "lamang": "only/just",
    "lubos": "completely/very",
    "bigla": "suddenly",
    "naman": "also/on the other hand",
    "talaga": "really/truly",
    "minsan": "sometimes",
    "bukas": "tomorrow", 
    "rito": "here", 
    "dito": "here", 
    "saan": "where", 
    "nasaan": "where is", 


    # Nouns (Includes translations for some common inflected forms)
    "bata": "child", "aso": "dog", "pusa": "cat", "bahay": "house", "pagkain": "food",
    "asin": "salt", "panahon": "weather/time", "guro": "teacher", "pangalan": "name",
    "banyo": "bathroom", "araw": "day/sun", "oras": "time/hour", "gabi": "night",
    "sinigang": "sinigang", "libro": "book", "tubig": "water", "kaligayahan": "happiness",
    "lahat": "everyone/all", "pamamagitan": "means", "eroplano": "airplane", "susi": "key",
    "kotse": "car", "salamin": "mirror/glasses", "bag": "bag", "payong": "umbrella",
    "taon": "year", "trabaho": "work/job", "silid": "room", "anak": "child/son/daughter",
    "lalaki": "man/male", "gulang": "age", "taong": "person",
    "opisina": "office", "mundo": "world", "tao": "person/human", "karangalan": "dignity",
    "karapatan": "rights", "katwiran": "reason", "budhi": "conscience", "diwa": "spirit",
    "pagkakapatiran": "brotherhood", "pakiusap": "request", "ideya": "idea", "kulay": "color",
    "gamot": "medicine", "botika": "pharmacy", "kaibigan": "friend", "salita": "word",
    "sipnayan": "mathematics", "parke": "park", "pasko": "christmas", "klase": "class/kind",
    "mestiza": "mestiza", "pagsusubok": "difficulty/trial", "paaralan": "school",
    "museo": "museum", "karne": "meat", "tingin": "opinion/look", "party": "party",
    "telepono": "telephone", "meeting": "meeting", "paliparan": "airport", "paglipad": "flight",
    "balita": "news", "estudyante": "student", "club": "club", "activities": "activities",
    "pangkat": "team/group", "tsismis": "rumor", "boss": "boss", "beach": "beach",
    "pag-asa": "hope", "pintura": "paint", "pagnanakaw": "theft", "computer": "computer",
    "kasangkapan": "tool/implement", "sanaysay": "essay", "pagkakaibigan": "friendship",
    "barko": "ship", "web": "web", "page": "page", "yugto": "stage/phase", "bagyo": "storm",
    "pakiramdam": "feeling", "problema": "problem/issue", "kapakanan": "welfare",
    "taong-bayan": "people/citizens", "camera": "camera", "kapatid": "sibling",
    "asong": "dog", "tiwala": "trust", "linggo": "week", "kaalamalam": "idea/knowledge",
    "pagsnow": "snowing/snowfall",
    "babae": "woman/female",
    "pera": "money",
    "lolo": "grandfather",
    "hapon": "afternoon", 

    "uri": "type/kind",
    "kape": "coffee",
    "puno": "tree/full",
    "tren": "train",
    "umaga": "morning",
    "gusali": "building",
    "makina": "machine",
    "ale": "german",
    "mund": "world",
    "dyaryo": "newspaper",
    "pagsasalita": "speaking",
    "hayop": "animal",
    "binhi": "seed",
    "mansanas": "apple",
    "atleta": "athlete",
    "tauhan": "staff",
    "digmaan": "war",
    "katotohanan": "truth",
    "lottery": "lottery",
    "ginhawa": "comfort/relief",
    "kalsada": "road",
    "lotto": "lotto", 
    "high": "high", 
    "school": "school", 
    "station": "station", 
    "bus": "bus", 


    # Adjectives (Includes translations for some common inflected forms)
    "maganda": "beautiful", "isang": "a/one", "mahal": "love/expensive", "mabuti": "good/fine",
    "maraming": "many", "mukhang": "looks like/seems", "bagong": "new",
    "malaya": "free", "pantay-pantay": "equal", "berde": "green", "masarap": "delicious/pleasant",
    "kainit": "hotness", "pagod": "tired", "sigurado": "sure/certain", "magkaiba": "different",
    "tatlong": "three", "ika-10": "tenth", "konti": "few/little", "mala-calculator": "calculator-like",
    "pinakamalalang": "worst", "pinakamahalagang": "most important", "totoo": "true/real",
    "susunod": "next", "malakas": "strong/loud",
    "mahirap": "difficult/poor",
    "unang": "first",
    "malapit": "near",
    "masamang": "bad",
    "putla": "pale",
    "mainit-init": "warmer",
    "kaakit-akit": "interesting",
    "mahina": "weak",
    "buong": "entire/whole",
    "naputla": "very pale",
    "payapa": "peaceful",
    "badtrip": "ticked off", 

    # Interjections
    "oo": "yes", "salamat": "thank you", "pasensya": "sorry", "tara": "let's go",
    "kumusta": "how is/are", "kamusta": "how is/are",
    "hoy": "hey",
    "nakuha": "got it?",

    # Interrogatives (Question Words)
    "ano": "what", "anong": "what", "saan": "where", "nasaan": "where is", "paano": "how",
    "gaano": "how much/many", "aling": "which", "kailan": "when",
    "sino": "who",
    "sino'ng": "who is",

    # Conjunctions
    "at": "and", "nang": "when/of/so that", "kaya": "so/maybe/can", "dahil": "because", "kahit": "even if/although",
    "kung": "if/when", "bago": "before", "tapos": "finished/then", "pero": "but",
    "kapag": "when/if",
    "mula": "from",
    "nang": "when",

    # Numbers
    "sampung": "ten", "19": "19", "30": "30",
    "tatlong": "three",
    "ika-5": "fifth",
    "ika-10": "tenth",

    # Other
    "ba": "(question particle)",
    "?": "?", 
    ".": ".", 
    ",": ",", 
    "!": "!", 
    "\"": "\"", 
    "-": "-", 

}
